### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#10]
Take or leave this suggestion as you wish, because if how you have it organized works for you, it works for you!  However, if you are rethinking organization in the future or migrating to a different technology, etc, I might recommend that you shovel a bunch of stuff into `assets` or a similarly named directory, or at least put the `images` in the same place.  That will help your repo code look a little less busy and group like-assets with each other.

Idk, I would probably do something like this if it were me, but it's really your preference if you decide to change anything or if you like how it is now!

```
onemorevoice
    / assets
        / css
        / js
        / fonts
        / images
            / objects
            / essays
            / motion-picture
            / etc
    / deploy-scripts
```

**Comment by awisnicki** [comment]
Thanks for this feedback. This was super helpful. Between that and the guidance on [this webpage](https://medium.com/@nmayurashok/file-and-folder-structure-for-web-development-8c5c83810a5), I developed a new folder structure. It's not as compressed as you recommended, but definitely much more compressed than before (and all images are indeed in one place now), plus better and more consistent file naming. It will also work well for me given the amount of dev I'm currently doing, and the constant need I have to be clicking down into directories. Please have a [look](https://github.com/livingstoneonline/onemorevoice/) when you have a moment. If you have any further suggestions, let me know, but otherwise please go ahead an close this issue once you've seen my comment.

**Comment by jduss4** [comment]
Looks great to me!
