### ISSUE TITLE
Deployment scripts and documentation

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#11]
I noticed `local-server.command` and I wonder if you might consider making it into either a true shell / bash script or putting it into your README, or both!

Your README right now is pretty bare bones in terms of development instructions or practices. It might be nice to have a section on local development, which could list the command you're using and how to check out the site.

If you foresee having more than one bash script at some point, you might also consider putting them all in the same directory so that they are kept separate from the actual site content.  I do that sometimes when I have a script for resizing images, and another script for renaming stuff, and another script for transforming TEI, etc.  It's nice to have them all in the same spot!

**Comment by awisnicki** [comment]
> I noticed `local-server.command` and I wonder if you might consider making it into either a true shell / bash script or putting it into your README, or both!

In terms of making a true shell / bash script, I'm not sure this is necessary. This command is really just for me to set up a local server when I'm testing the site. Re: README, see below.

> Your README right now is pretty bare bones in terms of development instructions or practices. It might be nice to have a section on local development, which could list the command you're using and how to check out the site.

Yes, fully agreed! In short, I need to do some documentation on how everything works. This is on my to-do list. I hadn't gotten as far as thinking about where I would put that documentation, so your suggestion about using the README file is great. I'll be sure to do that. Thank you. As I've been developing, I have been noting in various files where I get bits of coding, etc., so such documentation is scattered throughout the files, but I do agree that something more comprehensive and integrated is definitely needed.

> If you foresee having more than one bash script at some point, you might also consider putting them all in the same directory so that they are kept separate from the actual site content. I do that sometimes when I have a script for resizing images, and another script for renaming stuff, and another script for transforming TEI, etc. It's nice to have them all in the same spot!

Ha ha! When I first read this last week, I thought it not be necessary because in six months of running the site I'd so far only needed one bash script, but of course in the last week the need suddenly came up for a second one, so I've gone ahead and done as you suggested by creating a "bash" directory for my scripts. Thanks for that suggestion.

Please feel free to close this issue once you've seen my responses.
