### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#12]
Okay, first off I'm very impressed that the navigation is tabbable!  From the code I wouldn't have necessarily guessed it, but you put in a lot of work to make sure that it would be, and added a lot of aria information as well.

The real problem I have with it currently is that you need JavaScript to even see it.  Ideally, even if JavaScript is disabled, the navigation would show up (even if it's ugly).  So that's one hurdle you would need to clear in terms of how this is being added to each page if you're keeping your technology the same in the future.  One thing that we have done sometimes is to make the navigation very much visible by default, then use JS to detect if it's enabled and hide elements you don't want popping up in a page with JS enabled.  That way most users won't see a difference, but users without javascript will still see the navigation, even if it's not pretty to look at.

I haven't spent much time looking at the nav code, so sorry if this is already something you've already incorporated but you might be interested in looking at the w3 recommendations for making dropdown menus accessible.

https://www.w3.org/WAI/tutorials/menus/flyout/

In general, dropdown menus are tricky devils for accessibility and if you are migrating to another platform / tech I would recommend rethinking the nav and how to help users get around your site at the same time.

**Comment by awisnicki** [comment]
For the record, I was able to sort this out. Here's the code:

```
    checkUrl();
    
    function checkUrl () {
        if(location.pathname == "/" && 
            location.hash.length <= 1 && 
            location.search.length <= 1) {
                document.getElementById("home-tab").setAttribute("class","current");
        }
        if (window.location.href.indexOf("index") > -1) {	
                document.getElementById("home-tab").setAttribute("class","current");
        };
        if (window.location.href.indexOf("texts") > -1 ||
            window.location.href.indexOf("objects") > -1 ||
            window.location.href.indexOf("books") > -1 ||
            window.location.href.indexOf("motion") > -1 ||
            window.location.href.indexOf("essays") > -1 ||
            window.location.href.indexOf("_TEI") > -1 ||
            window.location.href.indexOf("_ART") > -1) {	
                document.getElementById("materials-tab").setAttribute("class","current");
        };
        if (window.location.href.indexOf("analytical") > -1 ||
            window.location.href.indexOf("design") > -1 ||
            window.location.href.indexOf("collaboration") > -1 ||
            window.location.href.indexOf("guidelines") > -1) {	
                document.getElementById("concepts-tab").setAttribute("class","current");
        };
        if (window.location.href.indexOf("contributors") > -1 ||
            window.location.href.indexOf("acknowledgments") > -1 ||
            window.location.href.indexOf("bibliography") > -1 ||
            window.location.href.indexOf("site_map") > -1) {	
                document.getElementById("misc-tab").setAttribute("class","current");
        };
    };
```

Ain't pretty, but it does the trick. If you have a suggestion for how to compress the repetitive bit of code (window.location.href.indexOf.....), please let me know. I haven't yet test this for when one is on root, but otherwise works well!

**Comment by awisnicki** [comment]
@jduss4 So there are two things cited in this issue:

1) Making the dropdowns accessible. The nav code does indeed include a number of features to make it accessible, so all set on that point.

2) No Javascript, no navigation. The advice you gave above for addressing this was great. Thank you! This turned out to be quite easy to resolve. First, I just hard coded a basic nav into the page I'm using at present for testing. That now shows up no matter what (I did add a touch of styling to make it a bit more bearable!). However, the head of the page now also includes a script that will only run if Javascript is enabled. The script hides the fallback nav and removes it from the DOM. So, in short, this is now sorted, and I'm going to go ahead and close this issue. So if Javascript enable, no ugly nav. Otherwise there it is!

Thanks again for the help with this!

**Comment by jduss4** [comment]
ha!  I should have read this issue before the other one I just commented on!  It sounds like you already came to the conclusion that I was recommending :)
