### ISSUE TITLE
Embedded CSS in HTML

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#5]
I am curious why you have chosen to embed CSS at the top of each HTML page, rather than just including it.  If you are concerned about load times, and want the bulk of the CSS to be loaded at the bottom of the page rather than the top, you could still just separate your CSS into multiple files, and then include one file at the top (taking the place of the copy-pasted CSS) and the rest at the bottom.

This would very much improve your ability to make changes to the CSS without having to change it in multiple files, plus it would make your individual HTML pages much less busy!

**Comment by awisnicki** [comment]
Thanks! This was great advice. Basically, the way this came about is that I was originally loading my entire CSS file at the start. Lighthouse indicated that this was slowing down the page and recommended that I inline critical CSS then load the rest at the end, so that's why I set it up in this way. However, you make some good points above, so I've gone ahead and put critical CSS in a separate file and now load that first (I also removed all the inline CSS), then at the end I load main CSS file. So this more or less keeps Lighthouse happy, but also simplifies editing along the lines you spell out above. Please feel free to close this issue once you've seen my comment.
