### ISSUE TITLE
Images in GitHub

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#7]
This is just a friendly warning that GitHub as a hosting platform does not necessarily love when you store images in your repository.  Some images for website function / design are fine, but having images for the various TEI pages may start eating up size.  I poked around and all your images are pretty small, so I don't think it's a big problem yet, but something to be aware of if you weren't already!

https://docs.github.com/en/github/managing-large-files/what-is-my-disk-quota

**Comment by awisnicki** [comment]
Thanks for drawing my attention to this. I had wondered what storage limits on GitHub are, but had never gotten around to looking into it, so good to have this info. I've been able to avoid issues (so far) with images eating up space because I use responsive images so all image are sized to be only as big as they appear on the screen (OMV also serves 2x versions of all images for screens with higher pixel density). There's also a bit of pre-publication compression that happens using ImageMagick. As a result, although the site includes over 1,300 images, at present the size is only 135 MB. So I'm not yet concern about images, but will keep this in mind going forward. Just out of curiosity, where would you suggest that I keep images if I don't keep them on GitHub so that they can still be easily integrated into the site?

**Comment by jduss4** [comment]
If you were using a more traditional webhost (rather than Github Pages) I would say it's not a problem to keep your images where they are alongside your other files. However, if storage space is a concern, then typically people would put their images on a different hosting platform altogether and point to them. So for example, the CDRH has all of our images stored on our server in the same place, and we get to them at `cdrhmedia.unl.edu/project/images/1823.jpg`. I keep my personal website images (don't go look at it, it's terribly under-developed!!) in Amazon S3.  I think your solution right now is probably fine if your smaller images are working for you in the site. Moving forward you may want to look into some options of actual dedicated image hosts if you are going to want larger / lots more images.

**Comment by awisnicki** [comment]
OK, thanks for clarifying this. This more or less correlates to what I was thinking in relation to your original post. As noted, it's not an issue now, but I'll keep it in mind in the future when it becomes relevant.
