### ISSUE TITLE
Cache Busting

### ISSUE THREAD

**Issue by jduss4** [livingstoneonline/onemorevoice#9]
Okay, I see why you are adding random strings to your CSS and JavaScript, but I must confess I don't like it!!! :) 

Web frameworks like django and rails have built in "fingerprinting" for files so that they will force the browser to download the new file when it is altered -- in this case, that's not that helpful for you since you are having to do it yourself, but I did want to stress that those only change the fingerprint when the file is updated. You have a clever solution to the cache busting but I don't love a few things about it....

1. This is a really weird way of loading CSS / JS!  I've seen weirder, but I worry that files just won't load if something has stopped the JS / JS is turned off, etc.
2. The random string changes on each request, which means the user will always have to download the CSS / JS files even if they already have a copy
3. I suspect there are other ways to get around cache busting, even if it's just like, working mostly locally on something and then when pushing a new change every few weeks, changing the numbers on the CSS / JS file yourself manually (like a version number)

Sorry to be critical of your solution!  It's definitely not something I'd ever come across before, so I give you points for solving the problem in a creative way!

**Comment by awisnicki** [comment]
> Okay, I see why you are adding random strings to your CSS and JavaScript, but I must confess I don't like it!!! :)

Note that random strings are also added to html files. For all these types of files this is due to the fact that the site is still in heavy development. Before you raised this issue my plan had been – as the site became more stable – to gradually remove the addition of random strings to these different kinds of files.

> Web frameworks like django and rails have built in "fingerprinting" for files so that they will force the browser to download the new file when it is altered -- in this case, that's not that helpful for you since you are having to do it yourself, but I did want to stress that those only change the fingerprint when the file is updated.

This goes back to the point of converting the site into a static site generator, so is also an issue I can come back to that that time as part of the general conversion process. See the comment I just made in #13.

>     1\. This is a really weird way of loading CSS / JS!  I've seen weirder, but I worry that files just won't load if something has stopped the JS / JS is turned off, etc.

I take your point :> Partly, I think, this will also be resolved when I tackle #4.

>     2\. The random string changes on each request, which means the user will always have to download the CSS / JS files even if they already have a copy

As noted, development is rather heavy at this time so that's OK. The good news is these files are pretty compact so that even if users need to reload them each time, there's no visible impact on performance and Google lighthouse is also not complaining. :>

>     3\. I suspect there are other ways to get around cache busting, even if it's just like, working mostly locally on something and then when pushing a new change every few weeks, changing the numbers on the CSS / JS file yourself manually (like a version number)

As things have turned out, I had started moving into this kind of workflow already where I work locally for a stretch of time then push changes up in a batch (rather than pushing them up one by one, which is what I was doing before). However, I'm still making a fair amount of changes regularly, so I'm much closer to the beginning than the end of this transition. For that same reason, I'm not changing version numbers manually which is an approach I had considered when I was first implementing the solution that I now have in place. However, the manual approach is something to which I could easily move over time as part of the larger transition to only the occasional push up from local, so I'll keep that in mind.

> Sorry to be critical of your solution! It's definitely not something I'd ever come across before, so I give you points for solving the problem in a creative way!

I'll take the points!

In any case, since this problem will get addressed under other work that I'm now planning, I'll go ahead and close this ticket. Thanks for this input!

**Comment by jduss4** [comment]
@awisnicki If you are mostly using the cache busting for local development, there should be settings in your browser that you can toggle on and off so that it will never cache.  I have my firefox set up so that it will never cache if the dev tools window is open, for example, which I find helpful for local development!  You may already be aware of that in which case, disregard my comment!

**Comment by awisnicki** [comment]
@jduss4 thanks! Just the opposite actually. Local is no big deal as I can always just do a refresh, but the average user won't do that (and might not even know to do that) as a matter of habit, so it's more the production version of the site that I want to ensure is up to date for people.
